trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables/variables.yaml

stages:
  - stage: Build
    displayName: "Build & Push Docker Image"

    jobs:
      - template: Templates/deploy-docker.yaml
        parameters:
          acrName: $(acrName)
          acrLoginServer: $(acrLoginServer)
          containerImage: $(aca-repo)
          dockerfilePath: 'Dockerfile'
          serviceConnection: 'my-work-helloworldd-portfolio'

  - stage: Deploy
    displayName: "Deploy Azure Container App"
    dependsOn: Build

    jobs:
      - template: Templates/container-app.yaml
        parameters:
          subscriptionId: $(subscriptionId)
          resourceGroupName: $(resourceGroupName)
          containerAppEnvName: $(containerAppEnvName)
          containerAppName: $(containerAppName)
          containerImage: "$(acrLoginServer)/$(aca-repo):$(Build.BuildId)"
          acrLoginServer: $(acrLoginServer)
          serviceConnection: 'my-work-helloworldd-portfolio'
      
