trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Development
    displayName: "Deploy Docker"

    variables:
      - template: variables/variables.yaml

jobs:
  - template: templates/deploy-docker.yaml
    parameters:
      acrName: $(acrName)
      acrLoginServer: $(acrLoginServer)
      imageName: $(imageName)
      dockerfilePath: $(dockerfilePath)
      clusterServiceConnection: $(serviceConnection)
