#Not Completed yet 

trigger: none

stages:
  - stage: Development
    displayName: "Deploy ACA Infrastructure"
    variables:
      variables:
         - template: variables/variables.yaml

    jobs:
      - template: Deploy-container-app.yaml
  

