trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Development
    displayName: "Deploy ACA Hello Worldd Infrastructure"

    variables:
      - template: variables/variables.yaml

    jobs:
      - template: Templates/Deploy-container-app-infra.yaml
        parameters:
          subscriptionId: $(subscriptionId)
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          acrName: $(acrName)
          logAnalyticsName: $(logAnalyticsName)
          containerAppEnvName: $(containerAppEnvName)
          containerAppName: $(containerAppName)
          containerImage: $(containerImage)
          serviceConnection: 'my-work-helloworldd-portfolio'

